# Generated by Django 5.0.4 on 2024-04-08 11:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('annee_publication', models.IntegerField(blank=True, null=True)),
                ('date_mise_en_ligne', models.DateField(auto_now_add=True)),
                ('nombre_telechargement', models.IntegerField(default=0)),
                ('genre', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='images/pdf_books/')),
                ('picture_books', models.FileField(upload_to='images/picture_books/')),
            ],
        ),
    ]
