# Generated by Django 5.0.4 on 2024-04-22 22:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='date_mise_en_ligne',
            new_name='date_online',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='nombre_telechargement',
            new_name='number_dowload',
        ),
        migrations.RemoveField(
            model_name='book',
            name='annee_publication',
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='status_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='type_book',
            field=models.CharField(default='Numeric', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='year_publication',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('books', models.ManyToManyField(to='backend.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
