# Generated by Django 5.0.4 on 2024-06-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Romance', 'Romance'), ('Biography', 'Biography'), ('Autobiography', 'Autobiography'), ('Business', 'Business'), ('Finance', 'Finance'), ('Personal Development', 'Personal Development'), ('Science', 'Science'), ('Guide', 'Guide'), ('Cooking', 'Cooking'), ('Technology', 'Technology'), ('Philosophy', 'Philosophy'), ('Religion', 'Religion'), ('Spirituality', 'Spirituality'), ('Economics', 'Economics'), ('Entrepreneurship', 'Entrepreneurship'), ('Politics', 'Politics'), ('Environment', 'Environment')], max_length=200),
        ),
    ]
