# Generated by Django 5.0.4 on 2024-05-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_date_mise_en_ligne_book_date_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='descritption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='images/pdf_books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='picture_books',
            field=models.FileField(blank=True, null=True, upload_to='images/picture_books/'),
        ),
    ]
