# Generated by Django 5.0.4 on 2024-06-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_book_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id',
            new_name='uid',
        ),
    ]
