# Generated by Django 5.0.4 on 2024-06-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_id_customuser_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='uid',
            new_name='uuid',
        ),
    ]
