# Generated by Django 5.0.4 on 2024-05-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_book_descritption_alter_book_pdf_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='descritption',
            new_name='description',
        ),
    ]
