# Generated by Django 5.0.4 on 2024-05-10 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
