# Generated by Django 5.0.4 on 2024-06-26 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_uuid_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritebookuser',
            name='book_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.bookversion'),
        ),
        migrations.AddField(
            model_name='favoritebookuser',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favoritebookuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='favoritebookuser',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.book'),
        ),
    ]
