# Generated by Django 5.0.4 on 2024-06-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_favoritebookuser_book_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
