# Generated by Django 5.0.4 on 2024-06-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_bookversion_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookversion',
            name='file',
            field=models.FileField(max_length=255, upload_to='book_versions/'),
        ),
        migrations.AlterField(
            model_name='bookversion',
            name='picture_file',
            field=models.FileField(max_length=255, upload_to='book_versions/covers/'),
        ),
    ]
