# Generated by Django 5.0.4 on 2024-07-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_bookversion_file_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritebookuser',
            unique_together={('user', 'book'), ('user', 'book_version')},
        ),
    ]
