# Generated by Django 5.0.4 on 2024-05-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_book_picture_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, default='default_pdf.pdf', null=True, upload_to='images/pdf_books/'),
        ),
    ]
