# Generated by Django 5.0.4 on 2024-05-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_book_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_publication',
            field=models.DateField(),
        ),
    ]
