# Generated by Django 5.0.4 on 2024-05-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_book_pdf_file_alter_book_picture_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture_books',
            field=models.FileField(upload_to='images/picture_books/'),
        ),
    ]
